name: check

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - id: flutter-version
        uses: ./.github/actions/tool-version
        with:
          tool: flutter

      # https://github.com/subosito/flutter-action
      - name: Setup flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          flutter-version: ${{ steps.flutter-version.outputs.version }}
          channel: stable
          cache: true
          cache-key: ${{ steps.flutter-version.outputs.version }}-stable

      # https://github.com/actions/cache
      - name: Cache dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ${{ env.PUB_CACHE }}
            ${{ github.workspace }}/.packages
            ${{ github.workspace }}/.flutter-plugins
            ${{ github.workspace }}/.flutter-plugin-dependencies
            ${{ github.workspace }}/.dart_tool/package_config.json
          key: build-pubspec-${{ hashFiles(format('{0}{1}', github.workspace, '/pubspec.lock')) }}
          restore-keys: |
            build-pubspec-

      - name: Install dependencies
        run: flutter pub get

      # https://github.com/invertase/github-action-dart-analyzer
      - name: Report analyze
        uses: invertase/github-action-dart-analyzer@e981b01a458d0bab71ee5da182e5b26687b7101b # v3
        with:
          fatal-infos: true

      - name: Run test
        run: flutter test --no-pub --machine > test_report.log
        continue-on-error: true

      # https://github.com/dorny/test-reporter
      - name: Report test
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
        with:
          name: "flutter test"
          path: "test_report.log"
          reporter: "flutter-json"
          fail-on-error: "true"
